export const SET_CATEGORY = 'STATIC:CATEGORY:SET'
export const ADD_CATEGORY = 'STATIC:CATEGORY:ADD'
export const DEL_CATEGORY = 'STATIC:CATEGORY:DEL'

export const SET_COLLECTION = 'STATIC:COLLECTION:SET'
export const ADD_COLLECTION = 'STATIC:COLLECTION:ADD'
export const DEL_COLLECTION = 'STATIC:COLLECTION:DEL'

export const SET_CONTACTS = 'STATIC:CONTACTS:SET'
export const ADD_CONTACTS = 'STATIC:CONTACTS:ADD'
export const DEL_CONTACTS = 'STATIC:CONTACTS:DEL'

export const CLEAR = 'STATIC:CLEAR'